- name: Install starship
  shell: curl -sS https://starship.rs/install.sh | sh -s -- --yes
  args:
    creates: /usr/local/bin/starship

- name: Ensure starship config directory exists
  file:
    path: "/home/{{ ansible_user }}/.config"
    state: directory

- name: Configure starship preset
  shell: starship preset pure -o /home/{{ ansible_user }}/.config/starship.toml
  become: no
